############################
# NAMOSKHAR TERMUX SETTINGS
############################

allow-external-apps=true

bell-character=ignore

terminal-margin-horizontal=2

terminal-margin-vertical=1

fullscreen=true

extra-keys = [ \
 ['ESC','CTRL','ALT','TAB','HOME','UP','END'], \
 ['`','|','/','LEFT','DOWN','RIGHT','BKSP'] \
]
